#+title Emacs Configuration New

#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

* Help
** Tangle file
org-babel-tangle
** Create block templates
<el<tab> (ensure that you don't have a closing tag [>] at the end of template block)
** To delete indentation in blocks
delete-horizontal-white space
** Autoformat
indent-region
** To edit blocks
C-c '

* Install
** Copy Straight.el bootstrap script below and paste into init.el
** Open emacs and Straight will install
** Open emacs.org and M-x org-babel-tangle
** Navigate to straight/repos, rm -rf nano emacs, and git clone jonroby/nano-emacs

* Setup (non-emacs)
** To change caps-lock to escape: Preferences -> Keyboard -> Modifier Keys
* Initialization
** Disable package.el from loading packages
#+begin_src emacs-lisp
(setq package-enable-at-startup nil)
#+end_src

** Straight.el

#+begin_src emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
#+end_src



* Read from Path
#+begin_src emacs-lisp
(straight-use-package 'exec-path-from-shell)
(when (memq window-system '(mac ns x))
  (exec-path-from-shell-initialize))
#+end_src

* Defaults
** Turn off annoying bell sound
#+begin_src emacs-lisp
(setq ring-bell-function 'ignore)
#+end_src

** Don't auto save
#+begin_src emacs-lisp
(setq auto-save-default nil)
#+end_src

** Don't create back up files
#+begin_src emacs-lisp
(setq make-backup-files nil)
#+end_src

** Don't create lock files
#+begin_src emacs-lisp
(setq create-lockfiles nil)
#+end_src

** Remove fringe
#+begin_src emacs-lisp
(set-fringe-mode 0)
#+end_src
* Editor
** Evil
*** Install
#+begin_src emacs-lisp
(setq evil-want-keybinding nil)

(straight-use-package 'evil)
(require 'evil)
(evil-mode 1)
#+end_src

*** Evil Collection
#+begin_src emacs-lisp
(straight-use-package 'evil-collection)
(evil-collection-init)
#+end_src

** Avy
*** Install
#+begin_src emacs-lisp
(straight-use-package 'avy)
(avy-setup-default)
#+end_src

*** Appearance
#+begin_src emacs-lisp
(with-eval-after-load 'avy
  (set-face-attribute 'avy-lead-face nil :background "#BF616A")
  (set-face-attribute 'avy-lead-face-0 nil :background "#5E81AC")
  )
#+end_src

** Drag Text
TODO: Can evil handle this?
#+begin_src emacs-lisp
(straight-use-package 'drag-stuff)
(require 'drag-stuff)

;; (drag-stuff-global-mode 1)
#+end_src

** Multiple cursors (multi-edit)
#+begin_src emacs-lisp
(straight-use-package 'evil-multiedit)
(require 'evil-multiedit)
(evil-multiedit-default-keybinds)
#+end_src

** General
For keybindings, navigate to Keybindings section
#+begin_src emacs-lisp
(straight-use-package 'general)
(require 'general)

(general-evil-setup t)
#+end_src

** Electric Pair
#+begin_src emacs-lisp
(electric-pair-mode 1)
#+end_src

* Navigation
** Helm
*** Install
#+begin_src emacs-lisp
(straight-use-package 'helm)
(require 'helm)
(helm-mode 1)
#+end_src

*** Swoop
#+begin_src emacs-lisp
(straight-use-package 'helm-swoop)
#+end_src

*** Stop TAB from using Dired
#+begin_src emacs-lisp
(define-key helm-map (kbd "TAB") #'helm-execute-persistent-action) 
#+end_src

*** Helm Modeline
Helm provides another mode line that provides useless information
This command removes it
#+begin_src emacs-lisp
(fset 'helm-display-mode-line #'ignore)
;; (add-hook 'helm-after-initialize-hook
;;           (defun hide-mode-line-in-helm-buffer ()
;;             "Hide mode line in `helm-buffer'."
;;             (with-helm-buffer
;;               (setq-local mode-line-format nil))))
#+end_src

** Projectile
*** Install
#+begin_src emacs-lisp
(straight-use-package 'projectile)
(require 'projectile)

(projectile-global-mode)
#+end_src

*** Caching
#+begin_src emacs-lisp
(setq projectile-enable-caching t)
#+end_src

*** Don't track projects automatically
#+begin_src emacs-lisp
(setq projectile-track-known-projects-automatically nil)
#+end_src

** Company

** Perspective
*** Install
#+begin_src emacs-lisp
(straight-use-package 'perspective)
#+end_src

*** Set default file to save to
#+begin_src emacs-lisp
;; (setq persp-state-default-file "~/.emacs.d/perspective/default")
#+end_src

** Vertico & Orderless
** Which Key
#+begin_src emacs-lisp
(straight-use-package 'which-key)
(which-key-mode)
#+end_src

* Typescript and Frontend Development
** Treemacs
#+begin_src emacs-lisp
;; (straight-use-package 'treemacs)
#+end_src

** Typescript
TODO: Javascript doesn't open as typescript
#+begin_src emacs-lisp
(straight-use-package 'typescript-mode)
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-mode))
(add-to-list 'auto-mode-alist '("\\.js\\'" . typescript-mode))
#+end_src

** Editorconfig
Reads .editorconfig from root directory
#+begin_src emacs-lisp
(straight-use-package 'editorconfig)
(editorconfig-mode 1)
#+end_src

** Prettier
No further configuration is needed for it to read from root directory (.prettierrc, etc.)
#+begin_src emacs-lisp
(straight-use-package 'prettier)
#+end_src

** Web mode
#+begin_src emacs-lisp
(straight-use-package 'web-mode)
#+end_src

* Applications
** Org Mode
*** Install
#+begin_src emacs-lisp
(straight-use-package 'org)
(require 'org)
#+end_src

*** Org agenda files
#+begin_src emacs-lisp
;; (setq org-agenda-files (directory-files-recursively "~/.emacs.d/org" "\.org$"))
#+end_src

*** Remove two spaces that are inserted when running emacs auto-indent in org-mode blocks
#+begin_src emacs-lisp
(setq org-src-preserve-indentation t)
#+end_src

*** Template blocks shortcut (el)
Org-tempo comes with org, so no need to install
#+begin_src emacs-lisp
(require 'org-tempo)

(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
#+end_src

*** Fix <return> bug
Pressing return causes the entire block to indent. This fixes issue.
#+begin_src emacs-lisp
(setq org-src-tab-acts-natively nil)
#+end_src

*** Org indent mode
#+begin_src emacs-lisp
(setq org-startup-indented t)
#+end_src

*** Appearance
**** Org background color
#+begin_src emacs-lisp
(with-eval-after-load 'org
  (set-face-attribute 'org-block nil :background "#27c12cf13750"))
#+end_src

**** Set ellipsis to down arrow
#+begin_src emacs-lisp
(setq org-ellipsis " ▾")
#+end_src

**** Org bullets
#+begin_src emacs-lisp
(straight-use-package 'org-bullets)
(require 'org-bullets)

(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src



** Magit
** Terminal
*** Vterm
brew install cmake libtool
If you receive prompt to compile, it might not recognize cmake 
See comments (and follow them exactly) for compilation https://github.com/akermu/emacs-libvterm/issues/169#issuecomment-568668946
#+begin_src emacs-lisp
(straight-use-package 'vterm)
#+end_src

*** Multi Vterm
#+begin_src emacs-lisp
(straight-use-package 'multi-vterm)
#+end_src

** TODO Rest Client

* IDE
** LSP
#+begin_src emacs-lisp
(straight-use-package 'lsp-mode)
#+end_src

*** LSP UI
#+begin_src emacs-lisp
(straight-use-package 'lsp-ui)
(setq lsp-ui-sideline-diagnostic-max-lines 20)
(setq lsp-ui-sideline-enable t)

(add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
#+end_src

*** LSP Treemacs
#+begin_src emacs-lisp
(straight-use-package 'lsp-treemacs)
(with-eval-after-load 'lsp-treemacs
  (set-face-attribute 'lsp-treemacs-file-error nil :foreground "#BF616A")) ;; left
#+end_src
*** Company
#+begin_src emacs-lisp
(straight-use-package 'company)

(setq gc-cons-threshold (* 100 1024 1024)
        read-process-output-max (* 1024 1024)
        company-idle-delay 0.0
        company-minimum-prefix-length 1
        create-lockfiles nil) ;; lock files will kill `npm start'
#+end_src

*** Customizations
#+begin_src emacs-lisp
(with-eval-after-load 'lsp-mode
    (setq lsp-headerline-breadcrumb-enable nil))
;;    (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
;;    (yas-global-mode))
#+end_src

** Flycheck
Note: LSP UI Sideline uses flycheck
#+begin_src emacs-lisp
(straight-use-package 'flycheck)
#+end_src

*** Appearance
#+begin_src emacs-lisp
(with-eval-after-load 'flycheck
  (set-face-attribute 'flycheck-info nil :underline '(:color "#EBCB8B" :style wave))
  (set-face-attribute 'flycheck-error nil :underline '(:color "#BF616A" :style wave))
  
  )
#+end_src

** Eslint

* Appearance
** Nano
Nano requires you to import the desired theme and after to call the function nano-faces and nano-theme.
#+begin_src emacs-lisp
(straight-use-package
  '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))

(require 'nano)
(require 'nano-theme-dark)

(require 'nano-faces)
(nano-faces)

(require 'nano-theme)
(nano-theme)
#+end_src

** Font
*** Font family
#+begin_src emacs-lisp
(set-face-attribute 'default nil
                    :family "SF Mono"
                    :height 130
                    :weight 'normal
                    :width 'normal)
#+end_src

** Title Bar
*** Make title bar same color as background
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
#+end_src

** Line Spacing
#+begin_src emacs-lisp
(setq-default line-spacing 2)
#+end_src



* Layers
** Helm Projectile
#+begin_src emacs-lisp
(straight-use-package 'helm-projectile)
(require 'helm-projectile)
(helm-projectile-on)
#+end_src

** Helm Ag
#+begin_src emacs-lisp
(straight-use-package 'helm-ag)
#+end_src

** LSP Helm
#+begin_src emacs-lisp
(straight-use-package 'helm-lsp)
#+end_src

* Keybindings
** General 
*** LSP
#+begin_src emacs-lisp
(general-create-definer lsp-leader-def
  :prefix "SPC l")

(lsp-leader-def
 :states 'normal
 "l" 'lsp
 "t" 'lsp-goto-type-definition
 "r" 'lsp-ui-peek-find-references
 "j" 'lsp-ui-peek-find-definitions
 "k" 'lsp-ui-peek-jump-backward
 "p" 'prettier-prettify
 )
#+end_src

*** Window
#+begin_src emacs-lisp
(general-create-definer window-leader-def
  :prefix "SPC w")

(window-leader-def
 :states 'normal
 "j" 'split-window-below
 "l" 'split-window-right
 "d" 'delete-window
 )
#+end_src

*** Buffer
#+begin_src emacs-lisp
(defun switch-to-last-buffer ()
  (interactive)
  (switch-to-buffer nil))

(general-create-definer buffer-leader-def
  :prefix "SPC b")

(buffer-leader-def
 :states 'normal
 "a" 'save-buffer
 "j" 'previous-buffer
 "k" 'next-buffer
 "l" 'switch-to-last-buffer
 "b" 'switch-to-buffer
 "d" 'kill-buffer
 )
#+end_src

*** Projectile
#+begin_src emacs-lisp
(general-create-definer projectile-leader-def
  :prefix "SPC p")

(projectile-leader-def
 :states 'normal
 "a" 'projectile-add-known-project
 "p" 'helm-projectile-switch-project
 "f" 'helm-projectile-find-file
 "t" 'helm-projectile-ag
 "b" 'projectile-display-buffer
 )
#+end_src

*** Emacs
#+begin_src emacs-lisp
(general-create-definer emacs-leader-def
  :prefix "SPC e")

(emacs-leader-def
 :states 'normal
 "q" 'save-buffers-kill-terminal
 "e" 'helm-M-x
 "y" 'helm-show-kill-ring
 "r" 'eval-last-sexp
 "i" '(lambda () (interactive) (find-file "~/.emacs.d/emacs.org"))
 )
#+end_src

*** Perspective
#+begin_src emacs-lisp
(general-create-definer emacs-leader-def
  :prefix "SPC v")

(emacs-leader-def
 :states 'normal
 "l" 'persp-list-buffers
 "s" 'persp-switch
 "k" 'persp-kill
 "b" 'persp-switch-to-buffer
 "n" 'persp-next
 "x" 'persp-remove-buffer
 "a" 'persp-set-buffer
 "A" 'persp-add-buffer
 "r" 'persp-rename
 "S" 'persp-state-save
 "L" 'persp-state-load
 )
#+end_src

*** Leader Keys
#+begin_src emacs-lisp
(general-create-definer jonroby/leader-keys
  :keymaps 'normal
  :prefix "SPC")

(jonroby/leader-keys
  "." 'helm-buffers-list
  "/" 'helm-find-files
  "s" 'helm-swoop
  "m" 'magit
  "a" 'save-buffer
  )
#+end_src

** Evil
*** Global
#+begin_src emacs-lisp
(evil-define-key '(normal visual) 'global (kbd ",") 'evil-scroll-down)
(evil-define-key '(normal visual) 'global (kbd ".") 'evil-scroll-up)

(evil-define-key '(normal) 'global (kbd "<DEL>") 'delete-backward-char)
(evil-define-key '(normal) 'global (kbd "M-n") 'drag-stuff-down)
(evil-define-key '(normal) 'global (kbd "M-p") 'drag-stuff-up)
(evil-define-key '(normal) 'global (kbd "C-o") 'open-line)
(evil-define-key '(normal) 'global (kbd "M-o") 'delete-blank-lines)
#+end_src

*** Motion
**** Move to last char on line for emacs
Vim doesn't use eol like emacs. However, with emacs you will want to evaluate functions, which requires you to be on eol and not on the last char.
#+begin_src emacs-lisp
(setq evil-move-beyond-eol t)
#+end_src

**** Function to go to last non blank character
#+begin_src emacs-lisp
(evil-define-motion evil-last-non-blank (count)
  "Move the cursor to the last non-blank character
  on the current line. If COUNT is given, move COUNT - 1
  lines downward first."
  :type inclusive
  (evil-end-of-line count)
  (re-search-backward "^\\|[^[:space:]]")
  (setq evil-this-type (if (eolp) 'exclusive 'inclusive)))
#+end_src

**** Keybindings
#+begin_src emacs-lisp
(define-key evil-motion-state-map "g-" 'evil-end-of-line)
(define-key evil-motion-state-map "-" 'evil-last-non-blank)
(define-key evil-motion-state-map "1" 'evil-first-non-blank-of-visual-line)
(define-key evil-motion-state-map "9" 'other-window)
(define-key evil-motion-state-map "f" 'avy-goto-word-1)
#+end_src


** Emacs
*** Copy full path to kill ring
#+begin_src emacs-lisp
(defun copy-full-path-to-kill-ring ()
  "copy buffer's full path to kill ring"
  (interactive)
  (when buffer-file-name
    (kill-new (file-truename buffer-file-name))))

(global-set-key (kbd "C-c y") 'copy-full-path-to-kill-ring)
#+end_src

* Appearance
** Company
#+begin_src emacs-lisp
(setq company-idle-delay 0)
(with-eval-after-load 'company
  (set-face-attribute 'company-tooltip nil :foreground "#5E81AC" :background "#27c12cf13750")
  (set-face-attribute 'company-tooltip-annotation nil :foreground "#4C566A" :background "#27c12cf13750")
  (set-face-attribute 'company-tooltip-common-selection nil :foreground "white" :background "#A3BE8C")
  (set-face-attribute 'company-tooltip-selection nil :foreground "white" :background "#434C5E")
  ;; (set-face-attribute 'company-tooltip-common nil :foreground "#A3BE8C" :background "#27c12cf13750")
  ;; (set-face-attribute 'company-tooltip-annotation-selection nil :foreground "#4C566A" :background "#A3BE8C")
  )
#+end_src

** Helm
#+begin_src emacs-lisp
(with-eval-after-load 'helm
  (set-face-attribute 'helm-buffer-process nil :foreground "#BF616A")
  (set-face-attribute 'helm-ff-directory nil :background "#2E3440" :foreground "RosyBrown")
  (set-face-attribute 'helm-ff-dotted-directory nil :background "#2E3440" :foreground "RosyBrown")
  (set-face-attribute 'helm-ff-file-extension nil :foreground "#81A1C1")
  (set-face-attribute 'helm-ff-executable nil :foreground "#EBCB8B")
  (set-face-attribute 'helm-ff-prefix nil :background "#2E3440" :foreground "#4C566A")
  (set-face-attribute 'helm-header-line-left-margin nil :background "#2E3440" :foreground "#4C566A")
  (set-face-attribute 'helm-separator nil :foreground "#2E3440"))

;;  '(orderless-match-face-0 ((t (:foreground "#A3BE8C" :weight normal)))))
#+end_src
*** Helm Swoop
#+begin_src emacs-lisp
(with-eval-after-load 'helm-swoop
  (set-face-attribute 'helm-swoop-target-word-face nil :background "#434C5E" :foreground "#A3BE8C"))
#+end_src

** LSP
#+begin_src emacs-lisp
(setq lsp-ui-sideline-diagnostic-max-lines 3)
(with-eval-after-load 'lsp-ui
  (set-face-attribute 'lsp-ui-peek-header nil :foreground "white" :background "#3B4252")
  (set-face-attribute 'lsp-ui-peek-footer nil :foreground "white" :background "#3B4252")
  (set-face-attribute 'lsp-ui-peek-highlight nil :foreground "#A3BE8C" :background "#27c12cf13750" :box nil)
  (set-face-attribute 'lsp-ui-peek-peek nil :background "#27c12cf13750") ;; left 
  (set-face-attribute 'lsp-ui-peek-list nil :background "#27c12cf13750") ;; right
  (set-face-attribute 'lsp-ui-peek-filename nil :foreground "RosyBrown")
  (set-face-attribute 'lsp-ui-peek-selection nil :foreground "white" :background "#A3BE8C")) 
#+end_src

** Org Mode
#+begin_src emacs-lisp
(with-eval-after-load 'org
  (set-face-attribute 'org-block nil :background "#27c12cf13750"))
#+end_src

** Error
#+begin_src emacs-lisp
(set-face-attribute 'error nil :foreground "#BF616A" :background "#2E3440")
#+end_src
* Miscellaneous
** Open hosts without having to change permissions
#+begin_src emacs-lisp
(defun hosts ()
  "Open /etc/hosts as root."
  (interactive)
  (find-file "/sudo::/etc/hosts"))
#+end_src

** Capslock key escape
#+begin_src emacs-lisp
(define-key key-translation-map (kbd "ESC") (kbd "C-g"))
#+end_src

** Indent dots
#+begin_src emacs-lisp
(straight-use-package 'highlight-indent-guides)

(setq highlight-indent-guides-method 'character)
(add-hook 'typescript-mode-hook 'highlight-indent-guides-mode)
#+end_src

* Emacs Custom Set Faces
** This is last resort
#+begin_src emacs-lisp
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(helm-M-x-key ((t (:extend t :foreground "#434C5E")))))
#+end_src


