#+title Emacs Configuration New

#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

Up To: Line 450

* Help
** Tangle file
org-babel-tangle
** Create block templates
<el<tab> (ensure that you don't have a closing tag [>] at the end of template block)
** To delete indentation in blocks
delete-horizontal-white space
** Autoformat
indent-region

* Install
** Copy Straight.el bootstrap script below and paste into init.el
** Open emacs and Straight will install
** Open emacs.org and M-x org-babel-tangle

* Initialization
** Disable package.el from loading packages
#+begin_src emacs-lisp
(setq package-enable-at-startup nil)
#+end_src

** Straight.el

#+begin_src emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; TODO Temporary
(global-set-key (kbd "C-c e") (lambda () (interactive) (find-file "~/.emacs.d/init.org")))
#+end_src

* Defaults
** Turn off annoying bell sound
#+begin_src emacs-lisp
(setq ring-bell-function 'ignore)
#+end_src

** Don't auto save
#+begin_src emacs-lisp
(setq auto-save-default nil)
#+end_src

** Don't create back up files
#+begin_src emacs-lisp
(setq make-backup-files nil)
#+end_src

** Don't create lock files
#+begin_src emacs-lisp
(setq create-lockfiles nil)
#+end_src


* Editor
** Evil
*** Install
#+begin_src emacs-lisp
(straight-use-package 'evil)
(require 'evil)
(evil-mode 1)
#+end_src

** Avy
This doesn't work atm.
#+begin_src emacs-lisp
(straight-use-package 'avy)
(avy-setup-default)
#+end_src

** Drag Text
TODO: Can evil handle this?
#+begin_src emacs-lisp
(straight-use-package 'drag-stuff)
(require 'drag-stuff)

;; (drag-stuff-global-mode 1)
#+end_src

** Multiple cursors (multi-edit)
#+begin_src emacs-lisp
(straight-use-package 'evil-multiedit)
(require 'evil-multiedit)
(evil-multiedit-default-keybinds)
#+end_src

** General
For keybindings, navigate to Keybindings section
#+begin_src emacs-lisp
(straight-use-package 'general)
(require 'general)

(general-evil-setup t)
#+end_src

* Navigation
** Helm
*** Install
#+begin_src emacs-lisp
(straight-use-package 'helm)
(require 'helm)
(helm-mode 1)
#+end_src

*** Swoop
#+begin_src emacs-lisp
(straight-use-package 'helm-swoop)
#+end_src

** Projectile

*** Install
#+begin_src emacs-lisp
(straight-use-package 'projectile)
(require 'projectile)

(projectile-global-mode)
#+end_src

*** Caching
#+begin_src emacs-lisp
(setq projectile-enable-caching t)
#+end_src

*** Don't track projects automatically
#+begin_src emacs-lisp
(setq projectile-track-known-projects-automatically nil)
#+end_src

** Company

** Perspective
** Vertico & Orderless

* Languages
** Treemacs
#+begin_src emacs-lisp
;; (straight-use-package 'treemacs)
#+end_src
** Typescript
#+begin_src emacs-lisp
(straight-use-package 'typescript-mode)
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . typescript-mode))
#+end_src


* Applications
** Org Mode
*** Install
#+begin_src emacs-lisp
(straight-use-package 'org)
(require 'org)
#+end_src

*** Org agenda files
#+begin_src emacs-lisp
(setq org-agenda-files (directory-files-recursively "~/.emacs.d/org" "\.org$"))
#+end_src

*** Remove two spaces that are inserted when running emacs auto-indent in org-mode blocks
#+begin_src emacs-lisp
(setq org-src-preserve-indentation t)
#+end_src

*** Template blocks shortcut (el)
Org-tempo comes with org, so no need to install
#+begin_src emacs-lisp
(require 'org-tempo)

(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
#+end_src

*** Fix <return> bug
Pressing return causes the entire block to indent. This fixes issue.
#+begin_src emacs-lisp
(setq org-src-tab-acts-natively nil)
#+end_src

*** TODO Org indent mode
This doesn't work atm.
#+begin_src emacs-lisp
(org-indent-mode)
(visual-line-mode 1)
#+end_src

*** Appearance
**** TODO Org background color
This doesn't work atm.
#+begin_src emacs-lisp
(require 'color)
(set-face-attribute 'org-block nil :background
                    (color-darken-name
                     (face-attribute 'default :background) 3))
#+end_src

**** Set ellipsis to down arrow
#+begin_src emacs-lisp
(setq org-ellipsis " ▾")
#+end_src

**** Org bullets
#+begin_src emacs-lisp
(straight-use-package 'org-bullets)
(require 'org-bullets)

(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src



** Magit
** Terminal
*** Vterm
#+begin_src emacs-lisp
(straight-use-package 'vterm)
#+end_src

*** Multi Vterm
#+begin_src emacs-lisp
(straight-use-package 'multi-vterm)
#+end_src

** Rest Client

* IDE
** LSP
#+begin_src emacs-lisp
(straight-use-package 'lsp-mode)
(straight-use-package 'lsp-ui)
(straight-use-package 'helm-lsp)
(straight-use-package 'lsp-treemacs)
#+end_src
*** Company
#+begin_src emacs-lisp
(straight-use-package 'company)

(setq gc-cons-threshold (* 100 1024 1024)
        read-process-output-max (* 1024 1024)
        company-idle-delay 0.0
        company-minimum-prefix-length 1
        create-lockfiles nil) ;; lock files will kill `npm start'
#+end_src

*** Customizations
#+begin_src emacs-lisp
(with-eval-after-load 'lsp-mode
    (setq lsp-headerline-breadcrumb-enable nil))
;;    (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)
;;    (yas-global-mode))
#+end_src
** Flycheck
** Eslint

* Appearance
** Nano
Nano requires you to import the desired theme and after to call the function nano-faces and nano-theme.
#+begin_src emacs-lisp
(straight-use-package
  '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))

(require 'nano)
(require 'nano-theme-dark)

(require 'nano-faces)
(nano-faces)

(require 'nano-theme)
(nano-theme)
#+end_src

** Font
*** Font family
#+begin_src emacs-lisp
(set-face-attribute 'default nil
                    :family "SF Mono"
                    :height 130
                    :weight 'normal
                    :width 'normal)
#+end_src

** Title Bar
*** Make title bar same color as background
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
#+end_src

** Line Spacing
#+begin_src emacs-lisp
(setq-default line-spacing 2)
#+end_src

* Layers
** Helm Projectile
#+begin_src emacs-lisp
(straight-use-package 'helm-projectile)
(require 'helm-projectile)
(helm-projectile-on)
#+end_src

* Keybindings
** General 
*** LSP
#+begin_src emacs-lisp
(general-create-definer lsp-leader-def
  :prefix "SPC l")

(lsp-leader-def
 :states 'normal
 "l" 'lsp
 "t" 'lsp-goto-type-definition
 "r" 'lsp-ui-peek-find-references
 "j" 'lsp-ui-peek-find-definitions
 "k" 'lsp-ui-peek-jump-backward
 )
#+end_src

*** Window
#+begin_src emacs-lisp
(general-create-definer window-leader-def
  :prefix "SPC w")

(window-leader-def
 :states 'normal
 "j" 'split-window-below
 "l" 'split-window-right
 "d" 'delete-window
 )
#+end_src

*** Buffer
#+begin_src emacs-lisp
(defun switch-to-last-buffer ()
  (interactive)
  (switch-to-buffer nil))

(general-create-definer buffer-leader-def
  :prefix "SPC b")

(buffer-leader-def
 :states 'normal
 "a" 'save-buffer
 "j" 'previous-buffer
 "k" 'next-buffer
 "l" 'switch-to-last-buffer
 "b" 'switch-to-buffer
 "d" 'kill-buffer
 )
#+end_src

*** Projectile
#+begin_src emacs-lisp
(general-create-definer projectile-leader-def
  :prefix "SPC p")

(projectile-leader-def
 :states 'normal
 "a" 'projectile-add-known-project
 "p" 'helm-projectile-switch-project
 "f" 'helm-projectile-find-file
 "b" 'projectile-display-buffer
 )
#+end_src

*** Emacs
#+begin_src emacs-lisp
(general-create-definer emacs-leader-def
  :prefix "SPC e")

(emacs-leader-def
 :states 'normal
 "q" 'save-buffers-kill-terminal
 "e" 'helm-M-x
 "y" 'helm-show-kill-ring
 "r" 'eval-last-sexp
 "i" '(lambda () (interactive) (find-file "~/.emacs.d/emacs.org"))
 )
#+end_src

*** Perspective
#+begin_src emacs-lisp
(general-create-definer emacs-leader-def
  :prefix "SPC v")

(emacs-leader-def
 :states 'normal
 "l" 'persp-list-buffers
 "s" 'persp-switch
 "k" 'persp-kill
 "b" 'persp-switch-to-buffer
 "n" 'persp-next
 "x" 'persp-remove-buffer
 "a" 'persp-set-buffer
 "A" 'persp-add-buffer
 "r" 'persp-rename
 "S" 'persp-state-save
 "L" 'persp-state-load
 )
#+end_src

*** Leader Keys
#+begin_src emacs-lisp
(general-create-definer jonroby/leader-keys
  :keymaps 'normal
  :prefix "SPC")

(jonroby/leader-keys
  "." 'helm-buffers-list
  "/" 'helm-find-files
  "s" 'helm-swoop
  "m" 'magit
  )
#+end_src

** Evil
*** Global
#+begin_src emacs-lisp
(evil-define-key '(normal visual) 'global (kbd ",") 'evil-scroll-down)
(evil-define-key '(normal visual) 'global (kbd ".") 'evil-scroll-up)

(evil-define-key '(normal) 'global (kbd "<DEL>") 'delete-backward-char)
(evil-define-key '(normal) 'global (kbd "M-n") 'drag-stuff-down)
(evil-define-key '(normal) 'global (kbd "M-p") 'drag-stuff-up)
(evil-define-key '(normal) 'global (kbd "C-o") 'open-line)
(evil-define-key '(normal) 'global (kbd "M-o") 'delete-blank-lines)
#+end_src

*** Motion
**** Move to last char on line for emacs
Vim doesn't use eol like emacs. However, with emacs you will want to evaluate functions, which requires you to be on eol and not on the last char.
#+begin_src emacs-lisp
(setq evil-move-beyond-eol t)
#+end_src

**** Function to go to last non blank character
#+begin_src emacs-lisp
(evil-define-motion evil-last-non-blank (count)
  "Move the cursor to the last non-blank character
  on the current line. If COUNT is given, move COUNT - 1
  lines downward first."
  :type inclusive
  (evil-end-of-line count)
  (re-search-backward "^\\|[^[:space:]]")
  (setq evil-this-type (if (eolp) 'exclusive 'inclusive)))
#+end_src

**** Keybindings
#+begin_src emacs-lisp
(define-key evil-motion-state-map "g-" 'evil-end-of-line)
(define-key evil-motion-state-map "-" 'evil-last-non-blank)
(define-key evil-motion-state-map "1" 'evil-first-non-blank-of-visual-line)
(define-key evil-motion-state-map "9" 'other-window)
(define-key evil-motion-state-map "f" 'avy-goto-word-1)
#+end_src


** Emacs
*** Copy full path to kill ring
#+begin_src emacs-lisp


(global-set-key (kbd "C-c y") 'copy-full-path-to-kill-ring)
#+end_src

* Appearance
** Company
#+begin_src emacs-lisp
(setq company-idle-delay 0)
(with-eval-after-load 'company
  (set-face-attribute 'company-tooltip nil :foreground "#5E81AC" :background "#27c12cf13750")
  (set-face-attribute 'company-tooltip-annotation nil :foreground "#4C566A" :background "#27c12cf13750")
  (set-face-attribute 'company-tooltip-annotation-selection nil :foreground "#4C566A" :background "#A3BE8C")
  (set-face-attribute 'company-tooltip-common-selection nil :foreground "white" :background "#A3BE8C")
  (set-face-attribute 'company-tooltip-common nil :foreground "#A3BE8C" :background "#27c12cf13750")
  (set-face-attribute 'company-tooltip-selection nil :foreground "white" :background "#A3BE8C"))
#+end_src

** LSP
#+begin_src emacs-lisp
(setq lsp-ui-sideline-diagnostic-max-lines 3)
(with-eval-after-load 'lsp-ui
  (set-face-attribute 'lsp-ui-peek-header nil :foreground "white" :background "#3B4252")
  (set-face-attribute 'lsp-ui-peek-footer nil :foreground "white" :background "#3B4252")
  (set-face-attribute 'lsp-ui-peek-highlight nil :foreground "#A3BE8C" :background "#27c12cf13750" :box nil)
  (set-face-attribute 'lsp-ui-peek-peek nil :background "#27c12cf13750") ;; left 
  (set-face-attribute 'lsp-ui-peek-list nil :background "#27c12cf13750") ;; right
  (set-face-attribute 'lsp-ui-peek-filename nil :foreground "RosyBrown")
  (set-face-attribute 'lsp-ui-peek-selection nil :foreground "white" :background "#A3BE8C")) 
#+end_src
* Miscellaneous
** Open hosts without having to change permissions
#+begin_src emacs-lisp
(defun hosts ()
  "Open /etc/hosts as root."
  (interactive)
  (find-file "/sudo::/etc/hosts"))
#+end_src

** Capslock key escapes
#+begin_src emacs-lisp
(define-key key-translation-map (kbd "ESC") (kbd "C-g"))
#+end_src

* Appearance


* TODO Later
** Melpa (24)
** Helm
*** Helm show only basename (565)
*** Helm hide modeline (569)
** [1] LSP (721)
** [5] Web mode (812)
** [4] Magit (824)
** [2] Flycheck (1142)
** [3] Perspective (1489)
** Snippets (639)
** Helm style customization (551)
** Helm show kill ring (style)
** Helm M-x buffer (style)
** Company styling (675)
** Custom colors (1790)
