#+title Emacs Configuration New

#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

Up To: Line 450

* Help
** Tangle file
org-babel-tangle
** Create block templates
<el<tab> (ensure that you don't have a closing tag [>] at the end of template block)
** To delete indentation in blocks
delete-horizontal-white space
** Autoformat
indent-region

* Install
** Copy Straight.el bootstrap script below and paste into init.el
** Open emacs and Straight will install
** Open emacs.org and M-x org-babel-tangle

* Initialization
** Disable package.el from loading packages
#+begin_src emacs-lisp
(setq package-enable-at-startup nil)
#+end_src

** Straight.el

#+begin_src emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; TODO Temporary  
(global-set-key (kbd "C-c e") (lambda () (interactive) (find-file "~/.emacs.d/emacs.org")))
#+end_src

* Defaults
** Turn off annoying bell sound
#+begin_src emacs-lisp
(setq ring-bell-function 'ignore)
#+end_src

** Don't auto save
#+begin_src emacs-lisp
(setq auto-save-default nil)
#+end_src

** Don't create back up files
#+begin_src emacs-lisp
(setq make-backup-files nil)
#+end_src

** Don't create lock files
#+begin_src emacs-lisp
(setq create-lockfiles nil)
#+end_src


* Editor
** Avy
** Multiple cursors
** Evil
** General

* Navigation
** Helm
*** Install
#+begin_src emacs-lisp
(straight-use-package 'helm)
(require 'helm)
(helm-mode 1)
#+end_src

 
** Perspective
** Vertico & Orderless
** Projectile

* Languages

* Applications
** Org Mode
*** Install
#+begin_src emacs-lisp
(straight-use-package 'org)
(require 'org)
#+end_src

*** Org agenda files
#+begin_src emacs-lisp
(setq org-agenda-files (directory-files-recursively "~/.emacs.d/org" "\.org$"))
#+end_src

*** Remove two spaces that are inserted when running emacs auto-indent in org-mode blocks
#+begin_src emacs-lisp
(setq org-src-preserve-indentation t)
#+end_src

*** Template blocks shortcut (el)
Org-tempo comes with org, so no need to install
#+begin_src emacs-lisp
(require 'org-tempo)

(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
#+end_src

*** Fix <return> bug
Pressing return causes the entire block to indent. This fixes issue.
#+begin_src emacs-lisp
(setq org-src-tab-acts-natively nil)
#+end_src

*** TODO Org indent mode
This doesn't work atm.
#+begin_src emacs-lisp
(org-indent-mode)
(visual-line-mode 1)
#+end_src

*** Appearance
**** TODO Org background color
This doesn't work atm.
#+begin_src emacs-lisp
(require 'color)
(set-face-attribute 'org-block nil :background
                    (color-darken-name
                     (face-attribute 'default :background) 3))
#+end_src

**** Set ellipsis to down arrow
#+begin_src emacs-lisp
(setq org-ellipsis " ▾")
#+end_src

**** Org bullets
#+begin_src emacs-lisp
(straight-use-package 'org-bullets)
(require 'org-bullets)

(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src



** Magit
** Terminal
** Rest Client

* IDE
** LSP
** Flycheck
** Eslint

* Appearance
** Nano
Nano requires you to import the desired theme and after to call the function nano-faces and nano-theme.
#+begin_src emacs-lisp
(straight-use-package
  '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))

(require 'nano)
(require 'nano-theme-dark)

(require 'nano-faces)
(nano-faces)

(require 'nano-theme)
(nano-theme)
#+end_src

** Font
*** Font family
#+begin_src emacs-lisp
(set-face-attribute 'default nil
                    :family "SF Mono"
                    :height 130
                    :weight 'normal
                    :width 'normal)
#+end_src

** Title Bar
*** Make title bar same color as background
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
#+end_src

** Line Spacing
#+begin_src emacs-lisp
(setq-default line-spacing 2)
#+end_src

* Customizations
** Appearance
** Keybindings
** Interactions


* TODO Later
** Melpa (24)
** exec-path-from-shell-initialize (61)
** Org-mode auto-tangle (319)
** Copy full path to kill ring (454)
** Helm
*** Helm Projectile (517)
*** Helm kill ring (548)
*** Helm style customization (551)
*** Helm show only basename (565)
*** Helm hide modeline (569)
